seed: 0

model: 'efficientnet' #choices=['vgg16', 'mobilenetv3', 'efficientnet', 'resnet18']
load_target: '' #
load_pretrained: ''
load_target_csd: False #
fp_only: True
fp_fixed: False
_1st_1last: False

alpha_init: 2
quant_scaler: False
quant_w: False
quant_x: False
eps: 0.

bitwidth_w: 4
intbit_w: 0
bitwidth_x: 4
intbit_x: 0

lr: 1.0e-2
noKL: False
optim: 'sgd'
batch_size: 128
weight_decay: 5.0e-4
lr_scheduler: True
n_epoch: 200

print_freq: 1
save_freq: 50
nosave_ckp: False